complete re-work to make it faster... it is...
changed slow commands and added the ability to change the color of the distro logo independently of the font color

diff --git a/debinfo b/debinfo
--- a/debinfo
+++ b/debinfo
@@ -1,15 +1,21 @@
 #!/bin/sh
 
-user=$USER@
-OS="$(lsb_release -sirc)"
+user="${USER}@"
+hostname="${HOSTNAME:-${hostname:-$(hostname)}}"
+host="$(cat /sys/devices/virtual/dmi/id/product_name)"
+OS="$(cat /etc/os-release | grep PRETTY_NAME | sed 's/PRETTY_NAME=//g'| sed 's/"//g')"
+gtktheme="$(grep gtk-theme-name ~/.config/gtk-3.0/settings.ini | sed 's/gtk-theme-name=//')"
+icontheme="$(grep gtk-icon ~/.config/gtk-3.0/settings.ini | sed 's/gtk-icon-theme-name=//')"
+termfont="$(gsettings get org.gnome.desktop.interface monospace-font-name | sed "s/'//g" | awk '{print $1}')"
+resolution="$(xrandr | grep \* | sed 's/59.95\*+//g')"
 #Desktop="${XDG_CURRENT_DESKTOP}"
 Kernel="$(uname -sr)"
 Uptime="$(uptime -p | sed 's/up //')"
 Packages="$(dpkg -l | grep -c ^i)"
 Shell="$(basename "$SHELL")"
-CPU="$(lscpu | grep Model\ name | sed 's/name:\ //' | sed "s/([^)]*)/()/g" | sed 's/[)(]//g')" 
-GPU="$(glxinfo -B | grep Device: | sed "s/([^)]*)/()/g" | sed 's/[)(]//g')"
-RAM="$(free -h | awk '/^Mem:/ {print $3 "/" $2}')"
+CPU="$(lscpu | grep Model\ name | awk '{print $4" "$5" "$6}')" 
+GPU="$(lspci | grep VGA | sed 's/[][]//g' | awk '{print $12" "$13" "$18" "$19}')"
+RAM="$(free -h | grep Mem: | awk '{print $3 "/" $2}')"
 IP="$(hostname -I | awk '{print $1}')"
 
 if [ -z "${WM}" ]; then
@@ -28,21 +34,63 @@ else
 
 fi
 
+# COLORS
+c1="\e[91m" # Red
+c2="\e[32m" # Light Green
+c3="\e[33m" # Yellow
+c4="\e[34m" # Calm Blue
+c5="\e[35m" # Violet
+c6="\e[36m" # Arch Blue
+c7="\e[37m" # White
+c8="\e[96m" # Cyan Blue 
+c9="\e[39m" # Light Grey
+c10="\e[40m" # Dark Grey
+c11="\e[95m" # Light Purple
+c12="\e[94m" # Light Blue
+c20="\e[0m" # Normal
 
-echo '          _,met$$$$$gg.        '            $user$(hostname)
-echo '       ,g$$$$$$$$$$$$$$$P.     '            OS: $OS
-echo '     ,g$$P""       """Y$$.".   '            $envtype: $WM		 
-echo '    ,$$P"              `$$$."  '            Kernel: $Kernel
-echo '   ,$$P       ,ggs.     `$$b:  '            Uptime: $Uptime
-echo '  `d$$"     ,$P""   .    $$$   '            Packages: $Packages
-echo '   $$P      d$"     ,    $$P   '            Shell: $Shell
-echo '   $$:      $$.   -    ,d$$"   '            CPU: $CPU
-echo '   $$\;      Y$b._   _,d$P     '            GPU: $GPU
-echo '   Y$$.    `.`"Y$$$$P""        '            RAM: $RAM      
-echo '   `$$b      "-.__             '		  IP:  $IP
-echo '    `Y$$                       '
-echo '     `Y$$.                     '
-echo '       `$$b.                   '
-echo '         `Y$$b.                '
-echo '            `"Y$b._            '
-echo '                `""""          '
+# An Error echo Wrapper
+err0r()
+{
+	echo >&2 "$(tput bold; tput setaf 1)[-] ERROR: ${*}$(tput sgr0)"
+	echo ""
+	exit 86
+}
+
+
+# A Warning echo wrapper
+warn ()
+{
+	echo >&2 "$(tput bold; tput setaf 3)[!] WARNING: ${*}$)tput sgr0)"
+	echo ""
+}
+
+
+
+# A Message echo Wrapper
+msg ()
+{
+	echo "$(tput bold; tput setaf 2)[+] ${*}$(tput sgr0)"
+}
+
+
+
+echo  ""
+echo ${c1}'          _,met$$$$$gg.        '   ${c8}$user${c20}$hostname
+echo ${c1}'       ,g$$$$$$$$$$$$$$$P.     '   ${c20}----------- 
+echo ${c1}'     ,g$$P""       """Y$$.".   '   ${c8}OS:  ${c20}$OS 			 
+echo ${c1}'    ,$$P"              `$$$."  '   ${c8}host:  ${c20}$host 
+echo ${c1}'   ,$$P       ,ggs.     `$$b:  '   ${c8}Kernel:  ${c20}$Kernel 
+echo ${c1}'  `d$$"     ,$P""   .    $$$   '   ${c8}Uptime:  ${c20}$Uptime          
+echo ${c1}'   $$P      d$"     ,    $$P   '   ${c8}Packages:  ${c20}$Packages         
+echo ${c1}'   $$:      $$.   -    ,d$$"   '   ${c8}Shell:  ${c20}$Shell 
+echo ${c1}'   $$\;      Y$b._   _,d$P     '   ${c8}Resolution:  ${c20}$resolution
+echo ${c1}'   Y$$.    `.`"Y$$$$P""        '   ${c8}GTK Theme:  ${c20}$gtktheme
+echo ${c1}'   `$$b      "-.__             '   ${c8}Icon Theme:  ${c20}$icontheme
+echo ${c1}'    `Y$$                       '   ${c8}Terminal:  ${c20}$TERM
+echo ${c1}'     `Y$$.                     '   ${c8}Terminal Font:  ${c20}$termfont
+echo ${c1}'       `$$b.                   '   ${c8}CPU:  ${c20}$CPU
+echo ${c1}'         `Y$$b.                '   ${c8}GPU:  ${c20}$GPU
+echo ${c1}'            `"Y$b._            '   ${c8}RAM:  ${c20}$RAM
+echo ${c1}'                `""""          '   ${c8}IP:   ${c20}$IP 
+echo ""
